esphome:
  name: lilygos3-ecowatt
  friendly_name: LiLyGoS3-EcoWatt
  platformio_options:
    board_upload.flash_size: 16MB
    board_upload.maximum_ram_size: 327680
    board_upload.maximum_size: 16777216
    board_build.partitions: "../../../custom_partitions.csv"
  #includes:
  #  - circle.h
    
external_components:
  - source: github://landonr/lilygo-tdisplays3-esphome
    components: [tdisplays3]

esp32:
  board: esp32-s3-devkitc-1
  variant: esp32s3
  framework:
    type: arduino

# Enable logging
logger:
  level: INFO

  
api:
  encryption:
    key: "e4AThsYUhxovYZmc6yat6NZuI/8JIgbUdz8glH5z+wU="

ota:
  password: "5320cd818066e2aa7c12c485bfac33c3"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password


time:
  - platform: homeassistant
    id: ha_time

output:
  - platform: ledc
    pin: GPIO38
    id: gpio38
    frequency: 2000

light:
  - platform: monochromatic
    output: gpio38
    name: "Backlight"
    restore_mode: RESTORE_DEFAULT_ON

    
sensor:
  - platform: homeassistant
    name: "Consommation Power"
    id: consumption_power
    entity_id: sensor.shelly_channel_1_power

  - platform: homeassistant
    name: "Sunology Power"
    id: sun_power
    entity_id: sensor.shelly_sunpower_channel_1_power
    
  - platform: homeassistant
    name: "Mining Monitor Power"
    id: mining_power
    entity_id: sensor.mining_monitor_power

  - platform: homeassistant
    name: "Energy_cost"
    id: cost
    entity_id: input_number.energy_cost
    

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      inverted: true
      mode:
        input: true
        pullup: true
    name: "short press button0"
    id: tdisplay_button_0
    on_click:
      min_length: 1ms
      max_length: 1000ms
      then:
        - display.page.show_previous: disp
        - component.update: disp


text_sensor:
  - platform: wifi_info
    ip_address:
      name: ESP IP Address
    ssid:
      name: ESP Connected SSID
    bssid:
      name: ESP Connected BSSID
    mac_address:
      name: ESP Mac Wifi Address
    scan_results:
      name: ESP Latest Scan Results



font:
  - file:
      type: gfonts
      family: Nunito Sans
      weight: 600
    id: nunito_25
    size: 25
  - file:
      type: gfonts
      family: Nunito Sans
      weight: 600
    id: nunito_12
    size: 12
  - file:
      type: gfonts
      family: Nunito Sans
      weight: 600
    id: nunito_10
    size: 10

color:
  - id: RED
    red: 100%
    green: 33%
    blue: 33%
  - id: RED2
    red: 95%
    green: 34%
    blue: 0%
  - id: BLUE
    red: 0%
    green: 0%
    blue: 100%
  - id: WHITE
    red: 100%
    green: 100%
    blue: 100%
  - id: GREEN
    red: 35%
    green: 100%
    blue: 64%
  - id: BLACK
    red: 0%
    green: 0%
    blue: 0%

display:
  - platform: tdisplays3
    id: disp
    update_interval: 0.001s
    rotation: 0
    pages:
      - id: energy_dashboard
        lambda: |-
          it.print(53,  22, id(nunito_12), WHITE, TextAlign::LEFT, "PUISSANCE");
          // Circles! Let's draw one with the center at [25,25] and a radius of 10
          it.circle(25, 25, 10);
          // ... and the same thing filled again
          it.filled_circle(25, 25, 10);
          it.filled_circle(it.get_width() / 2, it.get_height() / 2, 50 );
          it.filled_circle(it.get_width() / 2, it.get_height() / 2, 50 , 50,  BLUE);



          
      - id: other_dashboard
        lambda: |-
          it.print(50,  22, id(nunito_12), WHITE, TextAlign::LEFT, "HELLO");